
resolver: lts-7.0

# compiler: ghc-8.0.1.20161117    # ghc-8.0.2-rc1
compiler: ghc-8.0.1.20161213    # ghc-8.0.2-rc2
compiler-check: match-exact
setup-info:
  ghc:
    linux64:
      8.0.1.20161117:
        url: http://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-deb8-linux.tar.xz
        content-length: 112047972
        sha1: 6a6e4c9c53c71cc84b6966a9f61948542fd2f15a
      8.0.1.20161213:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc2/ghc-8.0.1.20161213-x86_64-deb8-linux.tar.xz
        content-length: 111894616
        sha1: 8c7ebec9bf96c0a37b4b27ebcd5372844cb61755

    macosx:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-apple-darwin.tar.xz
        content-length: 113379688
        sha1: 53ed03d986a49ea680c291540ce44ce469514d7c
      8.0.1.20161213:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc2/ghc-8.0.1.20161213-x86_64-apple-darwin.tar.xz
        content-length: 113359104
        sha1: d87048467786a7b9667aef0a78d7ffd8779425b2

    windows64:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-unknown-mingw32.tar.xz
        content-length: 155652048
        sha1: 74118dd8fd8b5e4c69b25df1644273fbe13177c7
      8.0.1.20161213:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc2/ghc-8.0.1.20161213-x86_64-unknown-mingw32.tar.xz
        content-length: 155494112
        sha1: a536228cb7265aef19b2842a2c81cfe9ca372e45

packages:
- challenges/
- compiler/
- lol/
- lol-apps/
- lol-benches/
- lol-cpp/
- lol-repa/
- lol-tests/

- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: 3fb349fc9fb4ed957ca847941afbe86cb5fa457b
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-io.git
    commit: f4c84a5c961345bf65059f555f21c6e8bf3070a1
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-cuda.git
    commit: cd8d31c24717ab1041057d1979113689ac79fead
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: feeb953ba05567d08c24f2f6c7b7ef008e60363b
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

- location:
    git:    https://github.com/tmcdonell/Lol-accelerate.git
    commit: 9a977a45159d0a146c4e0a29ea5aa952cb73d8d2
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/numeric-prelude-accelerate.git
    commit: b1c3630f09e9e45a26deac3c1fe6194b9eb40263
  extra-dep: true

- location:
    git:    https://github.com/bscarlet/llvm-general.git
    # commit: 529f9bf117b5ffd1ccf7ebeb679a97b3b1c67938  # 3.8
    commit: ec1ad5bd2112e7f64dbb43441b5e2075cf6ad8e7  # 3.9
  extra-dep: true
  subdirs:
    - 'llvm-general'
    - 'llvm-general-pure'

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- chaselev-deque-0.5.0.5
- cuda-0.7.5.1
- equational-reasoning-0.4.1.1
- ghc-typelits-natnormalise-0.4.6
- ghc-typelits-presburger-0.1.1.0
- http-client-0.5.4
- http-client-tls-0.3.3
- http-conduit-2.2.3
- libffi-0.1
# - llvm-general-3.5.1.2
# - llvm-general-pure-3.5.1.0
- monomorphic-0.0.3.3
- nist-beacon-0.2.0.0
- non-negative-0.1.1
- numeric-prelude-0.4.2
- nvvm-0.7.5.1
- storable-record-0.0.3.1
- syntactic-3.6.2
- tagged-transformer-0.8
- tree-view-0.5
- type-natural-0.7.1.1
- unique-0

# Override default flag values for local packages and extra-deps
flags:
  llvm-general:
    shared-llvm: true
  lol-accelerate:
    cuda: false
    llvm-cpu: false
    llvm-ptx: false
  accelerate:
    internal-checks: false
    unsafe-checks: false
    bounds-checks: true
    debug: false
    ekg: false
  accelerate-cuda:
    debug: false
  accelerate-llvm-native:
    debug: false
  accelerate-llvm-ptx:
    debug: false
    nvvm:  false

# Extra package databases containing global packages
extra-package-dbs: []

# vim: nospell

