
resolver: lts-7.0

# require at least ghc-8.0.2-rc1
compiler: ghc-8.0.1.20161117
compiler-check: match-exact
setup-info:
  ghc:
    linux64:
      8.0.1.20161117:
        url: http://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-deb8-linux.tar.xz
        content-length: 112047972
        sha1: 6a6e4c9c53c71cc84b6966a9f61948542fd2f15a
    macosx:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-apple-darwin.tar.xz
        content-length: 113379688
        sha1: 53ed03d986a49ea680c291540ce44ce469514d7c
    windows64:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-unknown-mingw32.tar.xz
        content-length: 155652048
        sha1: 74118dd8fd8b5e4c69b25df1644273fbe13177c7

packages:
- challenges/
- compiler/
- lol/
- lol-accelerate/
- lol-apps/
- lol-benches/
- lol-cpp/
- lol-repa/
- lol-tests/
- numeric-prelude-accelerate/

- location:
    git:    https://github.com/tmcdonell/accelerate.git
    commit: 020d326285947e2953cfe091dcedb037904ed37d
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-io.git
    commit: a5e73442fd987243de12bfb0c1ff7a87d701ea94
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-cuda.git
    commit: e5d6dbfcf557fb1dd8eb3f295272fffd19fa3029
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: 20d417aaee1d26f37255929ed604a6d364832bbb
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- non-negative-0.1.1
- numeric-prelude-0.4.2
- tagged-transformer-0.8
- syntactic-3.6.2
- type-natural-0.7.1.1
- equational-reasoning-0.4.1.1
- ghc-typelits-presburger-0.1.1.0
- monomorphic-0.0.3.3
- tree-view-0.5
- ghc-typelits-natnormalise-0.4.6
- nist-beacon-0.2.0.0
- storable-record-0.0.3.1
- unique-0
- chaselev-deque-0.5.0.5
- http-conduit-2.2.3
- http-client-0.5.4
- http-client-tls-0.3.3
- cuda-0.7.0.0
- libffi-0.1
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    unsafe-checks: false
    bounds-checks: true
    debug: false
    internal-checks: false

# Extra package databases containing global packages
extra-package-dbs: []

# vim: nospell

