
resolver: lts-7.0

packages:
- challenges/
- compiler/
- lol/
- lol-accelerate/
- lol-apps/
- lol-benches/
- lol-cpp/
- lol-repa/
- lol-tests/
- numeric-prelude-accelerate/

- location:
    git:    https://github.com/tmcdonell/accelerate.git
    commit: 020d326285947e2953cfe091dcedb037904ed37d
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-io.git
    commit: a5e73442fd987243de12bfb0c1ff7a87d701ea94
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-cuda.git
    commit: e5d6dbfcf557fb1dd8eb3f295272fffd19fa3029
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: 20d417aaee1d26f37255929ed604a6d364832bbb
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps:
- non-negative-0.1.1
- numeric-prelude-0.4.2
- tagged-transformer-0.8
- syntactic-3.6.2
- type-natural-0.7.1.1
- equational-reasoning-0.4.1.1
- ghc-typelits-presburger-0.1.1.0
- monomorphic-0.0.3.3
- tree-view-0.5
- ghc-typelits-natnormalise-0.4.6
- nist-beacon-0.2.0.0
- storable-record-0.0.3.1
- unique-0
- chaselev-deque-0.5.0.5
- cuda-0.7.0.0
- libffi-0.1
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0

# Override default flag values for local packages and extra-deps
flags:
  accelerate:
    unsafe-checks: false
    bounds-checks: true
    debug: false
    internal-checks: false

# Extra package databases containing global packages
extra-package-dbs: []
